### ISSUE TITLE
Use PackageExtensionTools.jl

### ISSUE THREAD

**Issue by juliohm** [JuliaML/DensityRatioEstimation.jl#55]
Refactor the code to use https://github.com/cjdoris/PackageExtensionTools.jl

**Comment by longemen3000** [comment]
i would recommend to wait until the code is merged into `Requires.jl`

**Comment by juliohm** [comment]
@longemen3000 you mean that PackageExtensionTools.jl will be merged into Requires.jl?

**Comment by longemen3000** [comment]
i suppose, check https://github.com/JuliaPackaging/Requires.jl/issues/114

**Comment by juliohm** [comment]
Can we use PackageExtensionTools.jl now on this package as an example? It
seems that the Requires.jl PR was merged.

Em ter., 30 de mai. de 2023 12:09, Andrés Riedemann <
***@***.***> escreveu:

**Comment by juliohm** [comment]
@longemen3000 what is the status quo now for these extension packages?

**Comment by longemen3000** [comment]
Now that it is merged, it is possible to give it a try

**Comment by juliohm** [comment]
@longemen3000 can you kindly help here again converting the manual approach to the new recommended approach with PackageExtensionCompat.jl? Is that the newest recommended approach?

**Comment by longemen3000** [comment]
let me ask, the main problem in this particular package is that some extensions require 2 external packages loaded (JuMP + IPOPT, for example) i don't know if that package supports that specific workflow

**Comment by juliohm** [comment]
This package requires 2 packages as you described. Does it mean that we
need to preserve the current approach? What if we drop support for Julia <
1.9, can we simplify the code organization?

Em seg., 3 de jul. de 2023 17:00, Andrés Riedemann ***@***.***>
escreveu:

**Comment by longemen3000** [comment]
https://github.com/cjdoris/PackageExtensionCompat.jl/issues/7

**Comment by longemen3000** [comment]
if you drop julia < 1.9, then you can drop requires too

**Comment by juliohm** [comment]
@longemen3000 could you help with a quick PR that drops Julia < v1.9 support? I will try to read the package extensions docs by the end of the week, but I am assuming that this specific case with DensityRatioEstimation.jl and its optional functionality that depends on multiple packages is a tricky case to get right.

**Comment by longemen3000** [comment]
wait a moment, i'll do it right now

**Comment by juliohm** [comment]
Fixed on master.
