### ISSUE TITLE
Confusing error message when no optimization package is loaded

### ISSUE THREAD

**Issue by salbalkus** [JuliaML/DensityRatioEstimation.jl#68]
Consider the following code snippet:

```
using DensityRatioEstimation
x = randn(100)
y = randn(100) .+ 1
DensityRatioEstimation.fit(KLIEP, x, y, LCV((σ=1,b=50)))
```

This throws `MethodError: no method matching iterate(::Nothing)`. The actual issue here, it appears, is that the necessary optimization package is not loaded; adding `using Optim` at the start fixes the problem. However, the error that is thrown obviously does not describe this problem accurately, making the problem difficult to debug for users unfamiliar with how DensityRatioEstimation.jl works. 

Perhaps it would be convenient to throw a more descriptive error when this occurs. I have found this package super useful and I think this could be a good quality-of-life addition.

**Comment by juliohm** [comment]
@salbalkus need some help to prepare a pull request?

https://github.com/firstcontributions/first-contributions

**Comment by salbalkus** [comment]
> @salbalkus need some help to prepare a pull request?
> 
> 
> 
> https://github.com/firstcontributions/first-contributions

Hi Júlio, thank you for the response and helpful link! I am preoccupied today but I can prepare a pull request next week 👍

**Comment by juliohm** [comment]
Fixed on master. Thanks!
